In [1]:
import pandas as pd
import numpy as np
import catboost

In [4]:
df = pd.read_csv('mid/FPL/TxG.csv')
df

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW29,GW30,GW31,GW32,GW33,GW34,GW35,GW36,GW37,GW38
0,208.0,80.0,14.0,384.0,151.0,166.0,102.0,238.0,309.0,179.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,113.0,113.0,108.0,280.0,185.0,104.0,220.0,156.0,116.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,113.0,143.0,138.0,58.0,108.0,196.0,199.0,295.0,198.0,141.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,208.0,179.0,129.0,70.0,152.0,115.0,193.0,170.0,136.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,121.0,119.0,160.0,125.0,178.0,100.0,223.0,83.0,95.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,155.0,336.0,105.0,114.0,371.0,72.0,323.0,66.0,255.0,218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,57.0,55.0,146.0,237.0,144.0,112.0,218.0,82.0,216.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,220.0,191.0,168.0,164.0,147.0,172.0,131.0,157.0,210.0,206.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,101.0,65.0,99.0,90.0,193.0,342.0,113.0,336.0,102.0,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,60.0,186.0,160.0,140.0,221.0,205.0,208.0,41.0,213.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,258.0,377.0,305.0,453.0,379.0,203.0,139.0,290.0,253.0,181.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,211.0,253.0,434.0,382.0,177.0,228.0,189.0,284.0,398.0,231.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,193.0,212.0,116.0,259.0,251.0,301.0,152.0,133.0,165.0,152.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,191.0,73.0,127.0,104.0,189.0,195.0,116.0,63.0,88.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,178.0,10.0,116.0,128.0,167.0,93.0,156.0,148.0,28.0,136.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,123.0,79.0,308.0,177.0,143.0,196.0,71.0,150.0,202.0,169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,131.0,168.0,225.0,15.0,72.0,96.0,224.0,221.0,97.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,169.0,117.0,124.0,66.0,205.0,164.0,75.0,74.0,246.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,314.0,209.0,255.0,145.0,133.0,213.0,229.0,274.0,182.0,313.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,219.0,291.0,177.0,194.0,102.0,129.0,79.0,161.0,104.0,147.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN